<?php

namespace App\View\Components\Layout;

use Closure;
use Illuminate\Contracts\View\View;
use App\View\Core\Abstract\IndentAbstract;

class Standard extends IndentAbstract
{
    /**
     * Create a new component instance.
     */
    public function __construct(
        public string $padding = '',
        public string $margin = '',
        public bool $hasEditSublayout = false,
        public bool $bgGray = false,
        public bool $overflowHidden = false,
        public bool $hasfooter = true,
        public array $navigationNodes = [],
    ) {
        //
    }

    protected function allowedPaddingClasses()
    {
        return [
            'normal' => 'pt-10',
            'default' => '',
            'md' => '',
            'sm' => ''
        ];
    }

    protected function allowedMarginClasses()
    {
        return parent::allowedMarginClasses(); // TODO: Change the autogenerated stub
    }

    public function getPaddingClass()
    {
        return $this->getAllowedValue($this->padding, $this->allowedPaddingClasses(), '');
    }

    public function getMarginClass()
    {
        return '';
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.layout.standard', [
            'indentStyles' => $this->buildIndentClasses()
        ]);
    }
}
